[server]
  host = "0.0.0.0"
  port = 3000
[[periphery.gpio.entities]]
  id = "light"
  name = "Main Light"
  kind = "light"
  pin = 10
[[periphery.gpio.entities]]
  id = "fan"
  name = "Main Fan"
  kind = "fan"
  pin = 12
[[periphery.pwm.entities]]
  id = "dimmable_light"
  name = "Dimmable Light"
  kind = "light"
  pin = 8
